spring.application.name=coursework
spring.datasource.url=jdbc:postgresql://localhost:5432/coursework
spring.datasource.username=postgres
spring.datasource.password=27062006

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect
spring.jpa.hibernate.ddl-auto=update
#or update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

token.signing.key=53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

spring.flyway.url=jdbc:postgresql://localhost:5432/coursework
spring.flyway.user=postgres
spring.flyway.password=27062006
#spring.flyway.enabled=true