CREATE SEQUENCE IF NOT EXISTS apartments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS appointments_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS appointments_reports_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS orders_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS orders_reports_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS rents_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS residential_complexes_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE apartments
(
    area                   DOUBLE PRECISION,
    floor                  INTEGER,
    price                  DOUBLE PRECISION,
    rooms                  INTEGER,
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    residential_complex_id BIGINT                                  NOT NULL,
    address                VARCHAR(255)                            NOT NULL,
    heating_type           VARCHAR(255),
    photo                  VARCHAR(255)                            NOT NULL,
    state_of_repair        VARCHAR(255),
    status                 VARCHAR(255)                            NOT NULL,
    title                  VARCHAR(255)                            NOT NULL,
    water_supply_type      VARCHAR(255),
    CONSTRAINT apartments_pkey PRIMARY KEY (id)
);

CREATE TABLE appointments
(
    apartment_id            BIGINT,
    appointment_date        TIMESTAMP WITHOUT TIME ZONE,
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id                 BIGINT,
    appointment_description VARCHAR(500)                            NOT NULL,
    CONSTRAINT appointments_pkey PRIMARY KEY (id)
);

CREATE TABLE appointments_reports
(
    appointment_id     BIGINT,
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    report_description VARCHAR(500)                            NOT NULL,
    CONSTRAINT appointments_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE orders
(
    apartment_id      BIGINT                                  NOT NULL,
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_date        TIMESTAMP WITHOUT TIME ZONE,
    user_id           BIGINT                                  NOT NULL,
    order_description VARCHAR(500)                            NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id)
);

CREATE TABLE orders_reports
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    order_id           BIGINT,
    report_description VARCHAR(255),
    CONSTRAINT orders_reports_pkey PRIMARY KEY (id)
);

CREATE TABLE rents
(
    deposit      DOUBLE PRECISION,
    end_date     date,
    price        DOUBLE PRECISION                        NOT NULL,
    start_date   date                                    NOT NULL,
    apartment_id BIGINT                                  NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id      BIGINT                                  NOT NULL,
    description  VARCHAR(255),
    status       VARCHAR(255)                            NOT NULL,
    CONSTRAINT rents_pkey PRIMARY KEY (id)
);

CREATE TABLE residential_complex_photos
(
    residential_complex_id BIGINT NOT NULL,
    photo                  VARCHAR(255)
);

CREATE TABLE residential_complexes
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    address                    VARCHAR(255),
    building_construction_type VARCHAR(255),
    description                VARCHAR(255),
    name                       VARCHAR(255),
    CONSTRAINT residential_complexes_pkey PRIMARY KEY (id)
);

CREATE TABLE user_favorites
(
    apartment_id BIGINT NOT NULL,
    user_id      BIGINT NOT NULL
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    role     VARCHAR(255)                            NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE apartments
    ADD CONSTRAINT apartments_address_key UNIQUE (address);

ALTER TABLE apartments
    ADD CONSTRAINT apartments_title_key UNIQUE (title);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT users_username_key UNIQUE (username);

ALTER TABLE orders
    ADD CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE rents
    ADD CONSTRAINT fk3ibgltk3lo51nss3qrv3l2igw FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE NO ACTION;

ALTER TABLE rents
    ADD CONSTRAINT fk3pf0l216l390r3ya1pk8wvxe9 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE orders_reports
    ADD CONSTRAINT fk4egobtfy6o80ghaje0x1ad4u3 FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE NO ACTION;

ALTER TABLE appointments_reports
    ADD CONSTRAINT fk717om6vhx3arhphopflbfa0ok FOREIGN KEY (appointment_id) REFERENCES appointments (id) ON DELETE NO ACTION;

ALTER TABLE appointments
    ADD CONSTRAINT fk886ced1atxgvnf1o3oxtj5m4s FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE orders
    ADD CONSTRAINT fkb2n5q9t80447x4pasp7y8m FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE NO ACTION;

ALTER TABLE appointments
    ADD CONSTRAINT fkh3sjxls7carki9imrg82stkud FOREIGN KEY (apartment_id) REFERENCES apartments (id) ON DELETE NO ACTION;

ALTER TABLE residential_complex_photos
    ADD CONSTRAINT fknreqi2bobdp3ax6sxl4u2p6b3 FOREIGN KEY (residential_complex_id) REFERENCES residential_complexes (id) ON DELETE NO ACTION;

ALTER TABLE apartments
    ADD CONSTRAINT fkojchlxyo2c4vnuimno5j9ef69 FOREIGN KEY (residential_complex_id) REFERENCES residential_complexes (id) ON DELETE NO ACTION;